version: '3.8'

services:
  database:
    image: vettrack-db
    build:
      context: ./vettrack-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vettrack_db
      - POSTGRES_USER=vettrack_user
      - POSTGRES_PASSWORD=vettrack_password
      - VETTRACK_ENV=dev
    volumes:
      - vettrack-db-data:/var/lib/postgresql/data
    networks:
      - vettrack-net

  auth-service:
    image: vettrack-auth-service
    build:
      context: ./Backend/vet_auth_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://vettrack_user:vettrack_password@database:5432/vettrack_db
    depends_on:
      - database
    networks:
      - vettrack-net

  business-service:
    image: vettrack-business-service
    build:
      context: ./Backend/vet-business-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/vettrack_db
      - SPRING_DATASOURCE_USERNAME=vettrack_user
      - SPRING_DATASOURCE_PASSWORD=vettrack_password
    depends_on:
      - database
    networks:
      - vettrack-net

  frontend:
    image: vettrack-frontend
    build:
      context: ./Frontend/vettrack
      args:
        - VITE_AUTH_URL=http://localhost:8000
        - VITE_CORE_URL=http://localhost:8080
    ports:
      - "8081:80"
    depends_on:
      - auth-service
      - business-service
    networks:
      - vettrack-net

volumes:
  vettrack-db-data:

networks:
  vettrack-net:
